### ISSUE TITLE
ffi

### ISSUE THREAD

**Issue by rubydesign** [xxuejie/mruby-gles#1]
Hi,

I just came across this because i want to use the raspberry pi's gpu from ruby (that's open gl 2 -es ?), and say this looks like a good start.

Having written several ruby extensions (for mri) i have recently learned that there is a less c heavy ad more portable way (across ruby implementations) called ffi. Do you know ?

And I wanted to ask do you have any plans to implement that function interface (all those vector and matrix oprators) ?

thx
Torsten

**Comment by xxuejie** [comment]
Sorry I was AFK for the whole weekend and I have to reply this now.

Thanks for your idea! Actually I'm aware of ffi, and I know of something that already works with mruby(https://github.com/mobiruby/mruby-cfunc).

Here's my reason that I chose not to use ffi: [Daniel](https://github.com/bovi) described at [here](http://mruby.sh/201212101231.html) one of the design principles of mrbgem. For convenience I will just quote it here:

> what we would love to have is no overhead at all if we don’t use mrbgems

For a MRI extension, I would definitely choose a ffi since it saves a lot of code, but for mruby whose primary target is embedded device(and maybe the web), I would really doubt if the benefits of enrolling ffi would outperform the overhead of adding a ffi layer.

One more less convincing reason would be that making libffi(which is the basis of [mruby-cfunc](https://github.com/MobiRuby/mruby-cfunc)) work in emscripten environment may bring additional problems. But since I haven't tried this, it may also be the case that there's no problem at all:)

So currently I would go with a hand-written extension of OpenGL ES, and if ffi becomes more and more popular in mruby as the time goes, I would definitely love to rewrite this gem using ffi:)

Yes, I believe Raspberry PI is also using OpenGL ES 2.0. In fact this is also one of the reason I build this gem separate from [webruby](https://github.com/xxuejie/webruby), I'm also interested in running mruby on my PI but I haven't got my PI connecting to the hotspot(via a USB wifi adapter)-_-

I was implementing the functions according to the specification of OpenGL ES 2.0 at [here](http://www.khronos.org/opengles/2_X/), yet I didn't find any vector or matrix operators described by you. Sorry I wasn't so familiar with OpenGL, can you show me where I can find all these _function interface_? I would definitely love to implement them if it helps with developing:)

**Comment by rubydesign** [comment]
Hi,
I'm sorry if i got things wrong, i really am very new to this. I had read on wikipedia that newer versions of opengl (above 2) are not using a fixed pipeline, but all s dynamic and there is a "language" for this.

I did have a look at a 100page spec where it is defined, but i can't find that anymore. What i did find is this http://www.opengl.org/documentation/glsl/ , which sort of supports this.
And https://github.com/Groovounet/glm which implements a c++ (header only) wrapper around this. 
I had even read some scientific articles that prove using this glm gives performance boosts. But actually too little for me to be interesting. Or too much learning just now.

Thanks for the mruby and mobiruby links. Sounds interesting. 

T.

**Comment by xxuejie** [comment]
Yes, you got that right. OpenGL ES 2.0 uses a specific language called **OpenGL Shading Language**(GLSL), which is quite similar to what you find in the GLSL link, an OpenGL ES version spec can be found at [here](http://www.khronos.org/registry/gles/specs/2.0/GLSL_ES_Specification_1.0.17.pdf). You may want to check if we are talking about the same thing.

I didn't know about GLM, sorry. Based on a few glimpse at the homepage, it kind of looks like a mathematical library using GLSL-based language with extensions. I guess this is not really what we usually use in OpenGL.

Note that I'm not so familiar with OpenGL, all those things I said above can be wrong. So if you or anyone reading this issue find that what I said is wrong, I would really appreciate it if you can leave a comment here and point it out:)

**Comment by xxuejie** [comment]
Close for now
