### ISSUE TITLE
Sample Code + GLES?

### ISSUE THREAD

**Issue by ashes999** [xxuejie/mruby-gles#2]
Hi,

Would it be possible to get a small sample project code to see how this works?

**Comment by xxuejie** [comment]
Yeah, I have this in my mind. The reason I haven't done anything on this has to do with the initialization code: This repo is aimed for at least 3 platforms: [webruby](https://github.com/xxuejie/webruby), iOS and Android. While things like GLUT is close to abandoned(please forgive me if I was wrong), each platform has its own way to launch a GLES context.

So the problem here is that I want to get myself familiar with all the 3 platforms before adding any ruby wrappers for initialization. Unfortunately, I'm kind of busy lately([mruby-js](https://github.com/xxuejie/mruby-js), visa preparation and other school stuffs). Really sorry there aren't so many updates.

That being said, I believe I can try to work on an iOS sample project first, and I will let you and everyone else know ASAP I got a working demo. Thanks for your suggestions!

**Comment by ashes999** [comment]
Okay, please keep me posted. I'm actually really interested in this project, although I intend to start with Windows first, then Android, not iOS. You might be able to get some code out of mobiruby for iOS-specific initialization (not sure how far along they are so far).

Thanks and keep me posted please! :)

**Comment by xxuejie** [comment]
Please correct me if I was wrong: do they have OpenGL ES implementations on Windows? I thought the ES version is only for embedded devices, so is there any way to work around this in Windows?

I will definitely check out mobiruby, but I think a simple wrapper will be enough for initialization:)

**Comment by ashes999** [comment]
You're right; OpenGL ES is a subset of OpenGL that works on embedded systems like phones. Windows supports full-blown OpenGL, so in theory, that should work with a subset like OpenGL ES.

I'll check in with you later; I need to sort out what to do next. Please let me know if you  make any progress, even if it's months from now :)

**Comment by ashes999** [comment]
(Two years later ...)

Having just discovered webruby, I am again back asking for sample code :)

**Comment by take-cheeze** [comment]
I don't know how much this helps but there is a old code I wrote to test whether GLFW with mruby-gles:
https://gist.github.com/take-cheeze/187d1486d8b8468571a5

**Comment by xxuejie** [comment]
Well, I know it's been two years, and I don't really want to make an excuse for me being lazy. But here's what I thought lately:
1. If all one needs to support is the web space, what I do suggest is following the sample at [here](http://blog.qiezi.me/posts/84792-happy-birthday-ruby-lost-in-javascript), and using one of the engine targeting the Web specifically. Notable names here include [three.js](http://threejs.org/) and [Famous](http://famous.org/). Web is rather a crappy space, and I tend to think those engines know more than a regular OpenGL ES based engine about the quirks.
2. On the other hand, if one plans to use OpenGL ES as a portable target across iOS, Android and Web, yes, I agree that we are lacking certain sample code. Having said that, I don't think this sounds that bad, since GLFW is [implemented](https://github.com/kripken/emscripten/blob/master/src/library_glfw.js) in emscripten, so chances are what already work in other platforms will work here. Again, I should probably craft a demo instead of making excuses :)
3. As of now, emscripten is only optimized for a [subset](http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html?highlight=opengl) of OpenGL ES(the WebGL-friendly part), so my idea is that it might be better to get to know what part consists of the WebGL friendly part, and making that part a priority before crafting a demo here.

If I recall correctly, those were my latest plans on this repo. After that, I gradually lose interest in the game industry due to flourishing of free-to-play games. My interest now is mainly focused on text-based roguelikes. So this repo fails to become my priority.

Having said that, I completely understand your feeling, and I really should've got working here. Sorry about that, I will try to shift this on top of my work-on-this-when-have-time list :)

**Comment by ashes999** [comment]
@xxuejie don't do it on my account. MRuby has a lot of potential for real, cross-platform games (web, mobile, and desktop) but it's a lot of work. Things have come a long way in two years.  

I'm not really happy with my non-Ruby stack, but it's too much work for one person to re-implement everything, so I guess I'll just wait another couple of years. FWIF, mruby-gles seemed the best option; there is a specific game engine (`minigame`), but I don't know if it would work with mruby.

Cheers!

**Comment by xxuejie** [comment]
@ashes999 I'm just speaking my thoughts loud here :)

In addition, with all those advancements in Vulkan, Metal, DirectX, etc, as well as my growing knowledge and preference for [data oriented design](http://www.dataorienteddesign.com/dodmain/), I now wonder if it is the right way that we expose OpenGL ES API directly to mruby.

On the one hand, less and less games are running on OpenGL these days(in fact the only significant platform running OpenGL I can think of is Android). With the diversity of graphics APIs, maybe we should have a low-level layer of code talking directly to OpenGL ES, Metal or whatever interface, and then expose that layer as API to Ruby.

On the other hand, Ruby is never a programming language designed for performance, perhaps it might be better to keep Ruby at a higher level as a scripting language for a game engine, which the engine itself is written in C/C++ or [Dart](https://news.ycombinator.com/item?id=9475825) talking to OpenGL ES, Metal or whatever low-level interface. This way the engine part can leverage whatever optimizations we might have for the bare-metal, and we can then enjoy the elegance of Ruby as a programming language for writing games.

So instead of `mruby-gles`, I really do think what we need here, is something like [love2d](https://love2d.org/) or [OpenFL](http://www.openfl.org/), but tailored for Ruby. Should that project exists, I will be more than happy to help port that platform to webruby. But the cruel truth is: we are still waiting for that project.

Given my awkward little experience on game programming, I'm never the person suitable for writing and maintaining such a big project. So what I can do here, is also to wait for some more time :)

TBH, my interest these days, has shifted from using webruby as a game medium to an education platform: with a growing number of people using Chromebooks, won't it be cool if we can build certain apps for them that they can use to write code and get feedback directly in the browser? No plugin is needed in this case, even an Internet is not an requirement(everything runs in the browser JS engine)! This is what I'm thinking right now, instead of trying to create games based on Ruby, and bare-metal OpenGL ES. The bar here is just too high, since your competitors might be using Unity or Unreal.

**Comment by ashes999** [comment]
@xxuejie  I'm also looking for "OpenFL" in Ruby, but nothing exists. I was interested in trying to build something like that using webruby/mruby, but it's too much work.

(begin off topic discussion)

If you're interested in educational platforms, you may be interested in [this MITx course on educational game design](https://www.edx.org/course/design-development-games-learning-mitx-11-127x), which is really excellent. (You don't need to compete with Unity or Unreal!)

**Comment by xxuejie** [comment]
Thanks for the link! Really interesting course!

But when I talked about educational platforms, I mean education on traditional CS courses, such as compilers, operating systems, computer architecture, etc, not anything related to games :)

While, with Unity and Unreal both roll out 2D kit, I still think if anyone wants to build a game engine, they are the major competitors :P

**Comment by ashes999** [comment]
I keep reading this and thinking. Right now, there really is no option or alternative. I don't know enough about OpenGL to meaningfully discuss this.

The [mruby minigame library](https://github.com/bggd/mruby-minigame) uses Allegro as the back-end. And there is an allegro gem for mruby. 

Is that a sufficient starting-point? Is it possible to have one set of compatible code across all platforms?

**Comment by xxuejie** [comment]
Yeah, Allegro is perhaps a viable choice. And there's [work](http://sourceforge.net/p/alleg/mailman/message/32466338/) done porting Allegro to emscripten, so maybe this is worth a try. However, I don't know if Allegro is attractive to devs these days, it seems to be a quite old library. Any idea?

Another thing I'm interested is [smalruby](https://github.com/smalruby/smalruby). While this is for CRuby, I wonder if we can port the same thing over to mruby.

I also remember back in the days, there is a [talk](http://confreaks.tv/videos/rubyconf2012-game-development-and-ruby) about writing an engine with mruby. But I assume the author is quite busy these days since there's not much activity in the [repo](https://github.com/cadwallion/spinel).

Regarding OpenGL, I guess my main point is: I don't see much benefits in creating a pure OpenGL ES wrapper. Instead we should work directly on building mruby wrappers for engines.

**Comment by ashes999** [comment]
I've never used Allegro myself.

Do you want to team up and give this a shot? It won't be a production-grade solution, necessarily, and Allegro may not be the best choice; but at least we'll get a working demo, a "technical proof-of-concept." Hopefully, others will come and either start swapping parts (eg. allegro => metal/opengl) or use that as inspiration for their own solutions.

I've used OpenFL quite a lot, and I think I can grok how it works. It's a good model to build around.

I would start with a "hello world" image, and get that working with desktop, then Android, then WebRuby. There's a lot of work around generating templates for platforms and stuff. Then, we can add more functionality (eg. text, sprite rotation, etc.)

What do you think?

**Comment by xxuejie** [comment]
Just to be clear: are you proposing we build a API layer using Allegro (or something else is find), then use mruby to write the full game?

This sounds interesting, so my anser is yes, I think we can team up and give it a shot. I myself never had the courage to design such a whole layer since I lack enough experience in game dev.

**Comment by ashes999** [comment]
Yes. We're looking at building out a technical proof-of-concept where we use MRuby, plus Allegro, to "write once" (one piece of Ruby script) and generate a Windows (or Linux) application, and an Android application, and a web application. 

The end goal is probably to make a full game; I'm actually (sadly?) more interested in finding out if we can achieve this, and getting the pieces in place.

I have tried this on a smaller scale (with XNA: writing wrappers to achieve "write once" code that works on MonoDroid and XNA for Windows equally), but I don't have enough experience either :)
